name: "Gemini PR Reviewer by Joell-Alex1"
description: "Reviews pull requests using Gemini AI"
author: "Joell-Alex1"

branding:
  icon: "eye"
  color: "purple"

inputs:
  gemini-api-key:
    description: "Gemini API key"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"