name: "AI Review"

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Joell-Alex1/Github_Tester@v1
        with:
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}